"""Motion library — canonical specs for every motion.

Add a new motion here and reference it by name in a motion_sets/*.toml file.
"""

import numpy as np

from tasknpoint_project.goal_cond_tracking.mdp import MotionCfg, MotionGoalCfg

MOTION_LIB: dict[str, MotionCfg] = {
  "right_kick": MotionCfg(
    name="right_kick",
    sampling_weight=1.0,
    sub_targets=[
      MotionGoalCfg(
        goal_type="position",
        goal_weight=100.0,
        source_link="right_foot",
        source_type="site",
        target_pos_mean={"x": 0.5, "y": -0.6, "z": -0.70},
        target_pos_std={"x": 0.10, "y": 0.20, "z": 0.01},
        target_phase_start=0.290,
        target_phase_end=0.297,
      ),
      MotionGoalCfg(
        goal_type="velocity",
        goal_weight=10.0,
        source_link="right_foot",
        source_type="site",
        target_phase_start=0.285,
        target_phase_end=0.302,
        target_vel_mean={"x": 1.0, "y": 0.0, "z": 0.0},
        target_vel_std={"x": 0.0, "y": 0.0, "z": 0.0},
      ),
      MotionGoalCfg(
        goal_type="orientation",
        goal_weight=10.0,
        source_link="right_foot",
        source_type="site",
        target_phase_start=0.290,
        target_phase_end=0.297,
        target_orientation_mean={"roll": 0.0, "pitch": 0.0, "yaw": -np.pi / 2},
        target_orientation_std={"roll": 0.0, "pitch": 0.0, "yaw": 0.0},
        orientation_axis="y",
      ),
    ],
  ),
  "left_kick": MotionCfg(
    name="left_kick",
    sampling_weight=1.0,
    sub_targets=[
      MotionGoalCfg(
        goal_type="position",
        goal_weight=100.0,
        source_link="left_foot",
        source_type="site",
        target_pos_mean={"x": 0.5, "y": 0.0, "z": -0.70},
        target_pos_std={"x": 0.10, "y": 0.20, "z": 0.01},
        target_phase_start=0.340,
        target_phase_end=0.347,
      ),
      MotionGoalCfg(
        goal_type="velocity",
        goal_weight=10.0,
        source_link="left_foot",
        source_type="site",
        target_phase_start=0.335,
        target_phase_end=0.352,
        target_vel_mean={"x": 1.0, "y": 0.0, "z": 0.0},
        target_vel_std={"x": 0.0, "y": 0.0, "z": 0.0},
      ),
      MotionGoalCfg(
        goal_type="orientation",
        goal_weight=10.0,
        source_link="left_foot",
        source_type="site",
        target_phase_start=0.340,
        target_phase_end=0.347,
        target_orientation_mean={"roll": 0.0, "pitch": 0.0, "yaw": np.pi / 2},
        target_orientation_std={"roll": 0.0, "pitch": 0.0, "yaw": 0.0},
        orientation_axis="y",
      ),
    ],
  ),
  "right_far_kick": MotionCfg(
    name="right_far_kick",
    sampling_weight=1.0,
    sub_targets=[
      MotionGoalCfg(
        goal_type="position",
        goal_weight=100.0,
        source_link="right_foot",
        source_type="site",
        target_pos_mean={"x": 0.5, "y": -1.2, "z": -0.70},
        target_pos_std={"x": 0.10, "y": 0.20, "z": 0.01},
        target_phase_start=0.404,
        target_phase_end=0.411,
      ),
      MotionGoalCfg(
        goal_type="velocity",
        goal_weight=10.0,
        source_link="right_foot",
        source_type="site",
        target_phase_start=0.399,
        target_phase_end=0.416,
        target_vel_mean={"x": 1.0, "y": 0.0, "z": 0.0},
        target_vel_std={"x": 0.0, "y": 0.0, "z": 0.0},
      ),
      MotionGoalCfg(
        goal_type="orientation",
        goal_weight=10.0,
        source_link="right_foot",
        source_type="site",
        target_phase_start=0.404,
        target_phase_end=0.411,
        target_orientation_mean={"roll": 0.0, "pitch": 0.0, "yaw": -np.pi / 2},
        target_orientation_std={"roll": 0.0, "pitch": 0.0, "yaw": 0.0},
        orientation_axis="y",
      ),
    ],
  ),
  "left_far_kick": MotionCfg(
    name="left_far_kick",
    sampling_weight=1.0,
    sub_targets=[
      MotionGoalCfg(
        goal_type="position",
        goal_weight=100.0,
        source_link="left_foot",
        source_type="site",
        target_pos_mean={"x": 1.0, "y": 0.6, "z": -0.70},
        target_pos_std={"x": 0.10, "y": 0.20, "z": 0.01},
        target_phase_start=0.401,
        target_phase_end=0.408,
      ),
      MotionGoalCfg(
        goal_type="velocity",
        goal_weight=10.0,
        source_link="left_foot",
        source_type="site",
        target_phase_start=0.396,
        target_phase_end=0.413,
        target_vel_mean={"x": 1.0, "y": 0.0, "z": 0.0},
        target_vel_std={"x": 0.0, "y": 0.0, "z": 0.0},
      ),
      MotionGoalCfg(
        goal_type="orientation",
        goal_weight=10.0,
        source_link="left_foot",
        source_type="site",
        target_phase_start=0.401,
        target_phase_end=0.408,
        target_orientation_mean={"roll": 0.0, "pitch": 0.0, "yaw": np.pi / 2},
        target_orientation_std={"roll": 0.0, "pitch": 0.0, "yaw": 0.0},
        orientation_axis="y",
      ),
    ],
  ),
  "forehand": MotionCfg(
    name="forehand",
    sampling_weight=1.0,
    sub_targets=[
      MotionGoalCfg(
        goal_type="position",
        goal_weight=100.0,
        source_link="racket_contact",
        source_type="site",
        target_pos_mean={"x": 0.5, "y": -0.6, "z": 0.0},
        target_pos_std={"x": 0.10, "y": 0.40, "z": 0.40},
        target_phase_start=0.306,
        target_phase_end=0.313,
      ),
      MotionGoalCfg(
        goal_type="velocity",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.300,
        target_phase_end=0.320,
        target_vel_mean={"x": 1.0, "y": 0.0, "z": 0.1},
        target_vel_std={"x": 0.0, "y": 0.0, "z": 0.2},
      ),
      MotionGoalCfg(
        goal_type="orientation",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.306,
        target_phase_end=0.313,
        target_orientation_mean={"roll": np.pi / 8, "pitch": 0.0, "yaw": -np.pi / 2},
        target_orientation_std={"roll": 0.1, "pitch": 0.0, "yaw": 0.0},
        orientation_axis="y",
      ),
    ],
  ),
  "backhand": MotionCfg(
    name="backhand",
    sampling_weight=1.0,
    sub_targets=[
      MotionGoalCfg(
        goal_type="position",
        goal_weight=100.0,
        source_link="racket_contact",
        source_type="site",
        target_pos_mean={"x": 0.5, "y": 0.6, "z": 0.0},
        target_pos_std={"x": 0.10, "y": 0.40, "z": 0.40},
        target_phase_start=0.368,
        target_phase_end=0.375,
      ),
      MotionGoalCfg(
        goal_type="velocity",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.360,
        target_phase_end=0.380,
        target_vel_mean={"x": 1.0, "y": 0.0, "z": 0.1},
        target_vel_std={"x": 0.0, "y": 0.0, "z": 0.2},
      ),
      MotionGoalCfg(
        goal_type="orientation",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.368,
        target_phase_end=0.375,
        target_orientation_mean={"roll": -np.pi / 8, "pitch": 0.0, "yaw": np.pi / 2},
        target_orientation_std={"roll": 0.1, "pitch": 0.0, "yaw": 0.0},
        orientation_axis="y",
      ),
    ],
  ),
  "two_step_forehand": MotionCfg(
    name="two_step_forehand",
    sampling_weight=1.0,
    sub_targets=[
      MotionGoalCfg(
        goal_type="position",
        goal_weight=100.0,
        source_link="racket_contact",
        source_type="site",
        target_pos_mean={"x": 0.5, "y": -1.2, "z": 0.0},
        target_pos_std={"x": 0.10, "y": 0.40, "z": 0.40},
        target_phase_start=0.394,
        target_phase_end=0.403,
      ),
      MotionGoalCfg(
        goal_type="velocity",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.390,
        target_phase_end=0.410,
        target_vel_mean={"x": 1.0, "y": 0.0, "z": 0.1},
        target_vel_std={"x": 0.0, "y": 0.0, "z": 0.2},
      ),
      MotionGoalCfg(
        goal_type="orientation",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.394,
        target_phase_end=0.403,
        target_orientation_mean={"roll": np.pi / 8, "pitch": 0.0, "yaw": -np.pi / 2},
        target_orientation_std={"roll": 0.1, "pitch": 0.0, "yaw": 0.0},
        orientation_axis="y",
      ),
    ],
  ),
  "two_step_backhand": MotionCfg(
    name="two_step_backhand",
    sampling_weight=1.0,
    sub_targets=[
      MotionGoalCfg(
        goal_type="position",
        goal_weight=100.0,
        source_link="racket_contact",
        source_type="site",
        target_pos_mean={"x": 0.5, "y": 1.2, "z": 0.0},
        target_pos_std={"x": 0.10, "y": 0.40, "z": 0.40},
        target_phase_start=0.448,
        target_phase_end=0.455,
      ),
      MotionGoalCfg(
        goal_type="velocity",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.440,
        target_phase_end=0.460,
        target_vel_mean={"x": 1.0, "y": 0.0, "z": 0.1},
        target_vel_std={"x": 0.0, "y": 0.0, "z": 0.2},
      ),
      MotionGoalCfg(
        goal_type="orientation",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.448,
        target_phase_end=0.455,
        target_orientation_mean={"roll": -np.pi / 8, "pitch": 0.0, "yaw": np.pi / 2},
        target_orientation_std={"roll": 0.1, "pitch": 0.0, "yaw": 0.0},
        orientation_axis="y",
      ),
    ],
  ),
  "stepback_forehand": MotionCfg(
    name="stepback_forehand",
    sampling_weight=1.0,
    sub_targets=[
      MotionGoalCfg(
        goal_type="position",
        goal_weight=100.0,
        source_link="racket_contact",
        source_type="site",
        target_pos_mean={"x": 0.5, "y": 0.1, "z": 0.0},
        target_pos_std={"x": 0.10, "y": 0.40, "z": 0.40},
        target_phase_start=0.333,
        target_phase_end=0.340,
      ),
      MotionGoalCfg(
        goal_type="velocity",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.328,
        target_phase_end=0.345,
        target_vel_mean={"x": 1.0, "y": 0.0, "z": 0.1},
        target_vel_std={"x": 0.0, "y": 0.0, "z": 0.2},
      ),
      MotionGoalCfg(
        goal_type="orientation",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.333,
        target_phase_end=0.340,
        target_orientation_mean={"roll": np.pi / 8, "pitch": 0.0, "yaw": -np.pi / 2},
        target_orientation_std={"roll": 0.1, "pitch": 0.0, "yaw": 0.0},
        orientation_axis="y",
      ),
    ],
  ),
  "stepback_backhand": MotionCfg(
    name="stepback_backhand",
    sampling_weight=1.0,
    sub_targets=[
      MotionGoalCfg(
        goal_type="position",
        goal_weight=100.0,
        source_link="racket_contact",
        source_type="site",
        target_pos_mean={"x": 0.5, "y": -0.1, "z": 0.0},
        target_pos_std={"x": 0.10, "y": 0.40, "z": 0.40},
        target_phase_start=0.398,
        target_phase_end=0.405,
      ),
      MotionGoalCfg(
        goal_type="velocity",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.390,
        target_phase_end=0.410,
        target_vel_mean={"x": 1.0, "y": 0.0, "z": 0.1},
        target_vel_std={"x": 0.0, "y": 0.0, "z": 0.2},
      ),
      MotionGoalCfg(
        goal_type="orientation",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.398,
        target_phase_end=0.405,
        target_orientation_mean={"roll": -np.pi / 8, "pitch": 0.0, "yaw": np.pi / 2},
        target_orientation_std={"roll": 0.1, "pitch": 0.0, "yaw": 0.0},
        orientation_axis="y",
      ),
    ],
  ),

  ################# new tennis motions with steps ##################
  "one_step_forehand": MotionCfg(
    name="one_step_forehand",
    sampling_weight=1.0,
    sub_targets=[
      MotionGoalCfg(
        goal_type="position",
        goal_weight=100.0,
        source_link="racket_contact",
        source_type="site",
        target_pos_mean={"x": 0.5, "y": -0.1, "z": 0.0},
        target_pos_std={"x": 0.10, "y": 0.40, "z": 0.40},
        target_phase_start=0.388,
        target_phase_end=0.395,
      ),
      MotionGoalCfg(
        goal_type="velocity",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.380,
        target_phase_end=0.410,
        target_vel_mean={"x": 1.0, "y": 0.0, "z": 0.1},
        target_vel_std={"x": 0.0, "y": 0.0, "z": 0.2},
      ),
      MotionGoalCfg(
        goal_type="orientation",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.380,
        target_phase_end=0.410,
        target_orientation_mean={"roll": -np.pi / 8, "pitch": 0.0, "yaw": np.pi / 2},
        target_orientation_std={"roll": 0.1, "pitch": 0.0, "yaw": 0.0},
        orientation_axis="y",
      ),
    ],
  ),

  "forehand_sidestep": MotionCfg(
    name="forehand_sidestep",
    sampling_weight=1.0,
    sub_targets=[
      MotionGoalCfg(
        goal_type="position",
        goal_weight=100.0,
        source_link="racket_contact",
        source_type="site",
        target_pos_mean={"x": 0.5, "y": -0.1, "z": 0.0},
        target_pos_std={"x": 0.10, "y": 0.40, "z": 0.40},
        target_phase_start=0.435,
        target_phase_end=0.441,
      ),
      MotionGoalCfg(
        goal_type="velocity",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.420,
        target_phase_end=0.455,
        target_vel_mean={"x": 1.0, "y": 0.0, "z": 0.1},
        target_vel_std={"x": 0.0, "y": 0.0, "z": 0.2},
      ),
      MotionGoalCfg(
        goal_type="orientation",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.420,
        target_phase_end=0.455,
        target_orientation_mean={"roll": -np.pi / 8, "pitch": 0.0, "yaw": np.pi / 2},
        target_orientation_std={"roll": 0.1, "pitch": 0.0, "yaw": 0.0},
        orientation_axis="y",
      ),
    ],
  ),

  "forehand_two_sidestep": MotionCfg(
    name="forehand_two_sidestep",
    sampling_weight=1.0,
    sub_targets=[
      MotionGoalCfg(
        goal_type="position",
        goal_weight=100.0,
        source_link="racket_contact",
        source_type="site",
        target_pos_mean={"x": 0.5, "y": -0.1, "z": 0.0},
        target_pos_std={"x": 0.10, "y": 0.40, "z": 0.40},
        target_phase_start=0.519,
        target_phase_end=0.527,
      ),
      MotionGoalCfg(
        goal_type="velocity",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.514,
        target_phase_end=0.542,
        target_vel_mean={"x": 1.0, "y": 0.0, "z": 0.1},
        target_vel_std={"x": 0.0, "y": 0.0, "z": 0.2},
      ),
      MotionGoalCfg(
        goal_type="orientation",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.514,
        target_phase_end=0.542,
        target_orientation_mean={"roll": -np.pi / 8, "pitch": 0.0, "yaw": np.pi / 2},
        target_orientation_std={"roll": 0.1, "pitch": 0.0, "yaw": 0.0},
        orientation_axis="y",
      ),
    ],
  ),

  "backhand_onehand": MotionCfg(
    name="backhand_onehand",
    sampling_weight=1.0,
    sub_targets=[
      MotionGoalCfg(
        goal_type="position",
        goal_weight=100.0,
        source_link="racket_contact",
        source_type="site",
        target_pos_mean={"x": 0.5, "y": -0.1, "z": 0.0},
        target_pos_std={"x": 0.10, "y": 0.40, "z": 0.40},
        target_phase_start=0.318,
        target_phase_end=0.324,
      ),
      MotionGoalCfg(
        goal_type="velocity",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.303,
        target_phase_end=0.339,
        target_vel_mean={"x": 1.0, "y": 0.0, "z": 0.1},
        target_vel_std={"x": 0.0, "y": 0.0, "z": 0.2},
      ),
      MotionGoalCfg(
        goal_type="orientation",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.303,
        target_phase_end=0.339,
        target_orientation_mean={"roll": -np.pi / 8, "pitch": 0.0, "yaw": np.pi / 2},
        target_orientation_std={"roll": 0.1, "pitch": 0.0, "yaw": 0.0},
        orientation_axis="y",
      ),
    ],
  ),

  "backhand_onehand_step": MotionCfg(
    name="backhand_onehand_step",
    sampling_weight=1.0,
    sub_targets=[
      MotionGoalCfg(
        goal_type="position",
        goal_weight=100.0,
        source_link="racket_contact",
        source_type="site",
        target_pos_mean={"x": 0.5, "y": -0.1, "z": 0.0},
        target_pos_std={"x": 0.10, "y": 0.40, "z": 0.40},
        target_phase_start=0.454,
        target_phase_end=0.460,
      ),
      MotionGoalCfg(
        goal_type="velocity",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.440,
        target_phase_end=0.475,
        target_vel_mean={"x": 1.0, "y": 0.0, "z": 0.1},
        target_vel_std={"x": 0.0, "y": 0.0, "z": 0.2},
      ),
      MotionGoalCfg(
        goal_type="orientation",
        goal_weight=10.0,
        source_link="racket_contact",
        source_type="site",
        target_phase_start=0.440,
        target_phase_end=0.475,
        target_orientation_mean={"roll": -np.pi / 8, "pitch": 0.0, "yaw": np.pi / 2},
        target_orientation_std={"roll": 0.1, "pitch": 0.0, "yaw": 0.0},
        orientation_axis="y",
      ),
    ],
  ),

}
