xml_path: "g1_27dof_deploy.xml"

policy_path: "/home/blake/tasknpoint/logs/rsl_rl/g1_tracking/kicks_no_ori.onnx"

motion_paths:
  - "artifacts/one_step_right_kick.npz"
  - "artifacts/one_step_left_kick.npz"
  - "artifacts/two_step_right_kick.npz"
  - "artifacts/two_step_left_kick.npz"
  # - "artifacts/two_baby_step_right_kick.npz"
  # - "artifacts/forehand_fast:v0/motion.npz"
  # - "artifacts/backhand_fast:v0/motion.npz"
  # - "artifacts/two_step_forehand_fast:v0/motion.npz"
  # - "artifacts/two_step_backhand_fast:v0/motion.npz"
  # - "artifacts/stepback_forehand_fast:v0/motion.npz"
  # - "artifacts/stepback_backhand_fast:v0/motion.npz"

home_pos_duration: 3.0

# PD gains per joint (29 DOF)
Kp: [40.179, 99.098, 40.179, 99.098, 28.501, 28.501,
     40.179, 99.098, 40.179, 99.098, 28.501, 28.501,
     40.179, 28.501, 28.501,
     14.251, 14.251, 14.251, 14.251, 14.251, 16.778, 16.778,
     14.251, 14.251, 14.251, 14.251, 14.251, 16.778, 16.778]
Kd: [2.558, 6.309, 2.558, 6.309, 1.814, 1.814,
     2.558, 6.309, 2.558, 6.309, 1.814, 1.814,
     2.558, 1.814, 1.814,
     0.907, 0.907, 0.907, 0.907, 0.907, 1.068, 1.068,
     0.907, 0.907, 0.907, 0.907, 0.907, 1.068, 1.068]

default_base_pos: [0, 0, 0.78, 1, 0, 0, 0]
default_joint_pos: [-0.312, 0.0, 0.0, 0.669, -0.363, 0.0,
                    -0.312, 0.0, 0.0, 0.669, -0.363, 0.0,
                     0.0, 0.0, 0.0,
                     0.2,  0.2, 0.0, 0.6, 0.0, 0.0, 0.0,
                     0.2, -0.2, 0.0, 0.6, 0.0, 0.0, 0.0]

action_scale: [0.548, 0.351, 0.548, 0.351, 0.439, 0.439,
               0.548, 0.351, 0.548, 0.351, 0.439, 0.439,
               0.548, 0.439, 0.439,
               0.439, 0.439, 0.439, 0.439, 0.439, 0.075, 0.075,
               0.439, 0.439, 0.439, 0.439, 0.439, 0.075, 0.075]

control_dt: 0.02
contact_phase: [0.293, 0.403, 0.407, 0.474, 0.403]
contact_duration: 1.0
ball_launch_velocity: [-2.0, 0.0, 3.0]

goals:
  - name: "one_step_right_kick_position"
    type: "position"
    vector: [0.3206, -0.3557, -0.7514]
    motion_index: 0
  # - name: "one_step_right_kick_velocity"
  #   type: "velocity"
  #   vector: [1.0, 0.0, 0.0]
  #   motion_index: 0
  # - name: "one_step_right_kick_orientation"
  #   type: "orientation"
  #   vector: [0.0, 0.0, -1.5708]
  #   motion_index: 0
  - name: "one_step_left_kick_position"
    type: "position"
    vector: [0.4484, 0.4820, -0.7188]
    motion_index: 1
  # - name: "one_step_left_kick_velocity"
  #   type: "velocity"
  #   vector: [1.0, 0.0, 0.0]
  #   motion_index: 1
  # - name: "one_step_left_kick_orientation"
  #   type: "orientation"
  #   vector: [0.0, 0.0, 1.5708]
  #   motion_index: 1
  - name: "two_step_right_kick_position"
    type: "position"
    vector: [0.4856, -0.7632, -0.7502]
    motion_index: 2
  # - name: "two_step_right_kick_velocity"
  #   type: "velocity"
  #   vector: [1.0, 0.0, 0.0]
  #   motion_index: 2
  # - name: "two_step_right_kick_orientation"
  #   type: "orientation"
  #   vector: [0.0, 0.0, -1.5708]
  #   motion_index: 2
  - name: "two_step_left_kick_position"
    type: "position"
    vector: [0.5222, 0.8246, -0.6967]
    motion_index: 3
  # - name: "two_step_left_kick_velocity"
  #   type: "velocity"
  #   vector: [1.0, 0.0, 0.0]
  #   motion_index: 3
  # - name: "two_step_left_kick_orientation"
  #   type: "orientation"
  #   vector: [0.0, 0.0, 1.5708]
  #   motion_index: 3
  # - name: "two_baby_step_right_kick_position"
  #   type: "position"
  #   vector: [0.4812, -0.0485, -0.7371]
  #   motion_index: 4
  # - name: "two_baby_step_right_kick_velocity"
  #   type: "velocity"
  #   vector: [1.0, 0.0, 0.0]
  #   motion_index: 4
  # - name: "two_baby_step_right_kick_orientation"
  #   type: "orientation"
  #   vector: [0.0, 0.0, -1.5708]
  #   motion_index: 4

