# Kicks-only motion subset.

[robot]
xml = "robots/g1_soccer_27dof.xml"

[registry]
train_prefix = "bwerner-california-institute-of-technology-caltech/csv_to_npz"
eval_prefix  = "bwerner-california-institute-of-technology-caltech-org/wandb-registry-motions"

[[motions]]
name    = "pickup_bench_to_floor"
enabled = true

[[motions]]
name    = "pickup_bench_to_floor_2"
enabled = true