# single pickup 
[robot]
xml = "robots/training/g1_27dof_training.xml"

[registry]
train_prefix = "bwerner-california-institute-of-technology-caltech/csv_to_npz"

[[motions]]
name    = "cast_pickup_1"
enabled = true

[[motions]]
name    = "cast_pickup_2"
enabled = true

[[motions]]
name    = "cast_pickup_3"
enabled = true

[[motions]]
name    = "cast_pickup_4"
enabled = true

[[motions]]
name    = "cast_pickup_5"
enabled = true

[[motions]]
name    = "cast_pickup_6"
enabled = true






